### ISSUE TITLE
Some more API keys

### ISSUE THREAD

**Issue by christoh** [joscha82/wattpilot#17]
Sorry, I hate .yaml and don't have any tools for it. So I cannot send a PR for wattpilot.yaml.

**cae/cak**: Set cae (bool) to true, if you want to use the go-eCharger API at https://&lt;serial number&gt;.api.v3.go-e.io/api. Read out cak (string) to get the access token. Whenever you set cae from false to true a new cak is generated automatically.

**fap**: bool, froniusAllowPause: Normally true. Set to false if your car disconnects when a charging pause occurs. Only VW ID.3/ID.4 seem to require this.

**fte**: froniusTripEnergy, int (maybe float but unlikely): Minimum energy in Watthours to charge in next trip mode.

**ftt**: froniusTripTime, int: Starting time of your next trip in seconds from midnight local time. 3600 = 01:00 am local time

**Comment by ahochsteger** [comment]
@christoh thanks for the information, all 5 api keys are already contained in the `wattpilot.yaml` (no special tools required, it's just plain text - more compact and easier to read/write than JSON) and I just checked that I was able to read and set those values without problems in the Wattpilot Shell.
The only think I could not confirm is that the `cak` token is re-generated every time you enable it. It has been generated if you enable it for the first time but then left the same after disabling/enabling `cae`. It changes though, if you write anything to `cak` which seems to trigger a re-generation of the access token.
I'll update the documentation accordingly.

**Comment by ahochsteger** [comment]
The PR #19 resolves this issue.

**Comment by christoh** [comment]
Thanks for hacking it in. I can confirm cak re-generation occurs only if you write something to cak. To trigger you have to:

1) write something to cak (it does not seem possible to write your own custom token)
2) Disable cae (if it was enabled)
3) Enable cae

If you omit step 1, nothing happens
