### ISSUE TITLE
Upload to PyPI

### ISSUE THREAD

**Issue by mk-maddin** [joscha82/wattpilot#3]
Hi,

would you mind uploading this package to PyPI?
I understand as you said this is still in an early development stage - never the less it is the best module I found to interact with the wattpilot and an updload to PyPI would allow the re-useage of it in other projects like Home Assistant integration :)

Thanks

**Comment by joscha82** [comment]
Hi,
it is actually the plan to use this package as a base for a HA Integration. I had not found the time to create the HA Integration yet.
I will create a package sometime next week.

**Comment by mk-maddin** [comment]
Hi @joscha82,

I have just released a first draft version for [wattpilot home assistant integration](https://github.com/mk-maddin/wattpilot-HA).
So would be great to see the package within PyPI for automatic module installation :)

Thanks

**Comment by thecem** [comment]
Hi @joscha82, it would be really great to see the package within PyPI for automatic module installation. I Tried everything to get it work for HA OS, but everything faild! It would be really nice, if you could add it to pypi.....

Thank you so much!

**Comment by joscha82** [comment]
Hi,
now available on pypi: https://pypi.org/project/wattpilot/  ;)

**Comment by mk-maddin** [comment]
works like charm - thank you 
awesome :)

**Comment by thecem** [comment]
Thank you so much!
