### ISSUE TITLE
'Wattpilot' object has no attribute 'wsapp'

### ISSUE THREAD

**Issue by MugurelS** [joscha82/wattpilot#4]
Hi,

I'm trying to connect a Wattpilot 22j  Firmware version 36.3

python3.9 shell.py ip password "get amp"
ERROR:websocket:error from callback <bound method Wattpilot.__on_message of <wattpilot.Wattpilot object at 0xb6183fa0>>: 'Wattpilot' object has no attribute 'wsapp'
ERROR: Timeout while connecting to Wattpilot!

I there something I can do?

Thank you!

**Comment by joscha82** [comment]
Should be fixed now in master. Error was related to internal handling of connection issues. Most likely you triggered the bug by providing a wrong password.

**Comment by mze9412** [comment]
Works now for me!
